version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
    networks:
      - dev
    restart: always  # Автоматический перезапуск

  backend:
    build:
      context: ./backend
    networks:
      - dev
    restart: always  # Автоматический перезапуск

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    restart: always  # Автоматический перезапуск

networks:
  dev:
